# All the melodies were made or generated by StrangerWS
define audio.sudden_awakening_loop = "res/audio/music/sudden-awakening-loop.mp3"
define audio.battle_hymn = "res/audio/music/battle_hymn.mp3"
define audio.dark_echo = "res/audio/music/dark-echo.mp3"